# Generated by Django 4.2.6 on 2023-10-15 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作者",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="plate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.plate",
                verbose_name="板块",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="标签",
            ),
        ),
        migrations.AddField(
            model_name="plate",
            name="moderators",
            field=models.ManyToManyField(
                through="posts.ManagePlate",
                to=settings.AUTH_USER_MODEL,
                verbose_name="版主",
            ),
        ),
        migrations.AddField(
            model_name="manageplate",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="版主",
            ),
        ),
        migrations.AddField(
            model_name="manageplate",
            name="plate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.plate",
                verbose_name="板块",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="manageplate", unique_together={("plate", "moderator")},
        ),
    ]
