# Generated by Django 4.2.6 on 2023-10-22 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="plate", name="moderators",),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.AlterField(
            model_name="manageplate",
            name="moderator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managePlates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="版主",
            ),
        ),
        migrations.AlterField(
            model_name="manageplate",
            name="plate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderators",
                to="posts.plate",
                verbose_name="板块",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="coverImg",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/covers/", verbose_name="封面"
            ),
        ),
        migrations.CreateModel(
            name="LikeUserPost",
            fields=[
                (
                    "likeID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="点赞ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="点赞时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoLikes",
                        to="posts.post",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likePosts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"ordering": ("-created",), "unique_together": {("post", "user")},},
        ),
        migrations.CreateModel(
            name="CollectUserPost",
            fields=[
                (
                    "collectID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="收藏ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoCollects",
                        to="posts.post",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectPosts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"ordering": ("-created",), "unique_together": {("post", "user")},},
        ),
    ]
