# Generated by Django 4.2.6 on 2023-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "commentID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="评论ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, verbose_name="最后修改时间"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={"abstract": False,},
        ),
    ]
