# Generated by Django 4.2.6 on 2023-10-22 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childComments",
                to="comments.comment",
                verbose_name="父评论",
            ),
        ),
        migrations.CreateModel(
            name="LikeUserComment",
            fields=[
                (
                    "likeUserCommentID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="点赞评论ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoLikes",
                        to="comments.comment",
                        verbose_name="评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likeComments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"ordering": ("-created",),},
        ),
        migrations.CreateModel(
            name="CollectUserComment",
            fields=[
                (
                    "collectUserCommentID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="收藏评论ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whoCollects",
                        to="comments.comment",
                        verbose_name="评论",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectComments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"ordering": ("-created",),},
        ),
    ]
